#! /bin/bash
#: Name             : Duy Le-Dinh
#: Student Number   : 1403722
#: Description      : Exercise 5, Lab 3

## Funtion to calculate Age
function _calculate_age() {
  ## Get current day, month and year
  local curday=$( date +%d )
  local curmonth=$( date +%m )
  local curyear=$( date +%Y )

  _CALCULATE_AGE=$(( $curyear - $3 ))

  if [ $3 -eq $curyear ]
  then
   _CALCULATE_AGE=0
    return 0
  fi

  ## Check for month and day
  [ $2 -eq $curmonth ] && [ $1 -gt $curday ] && _CALCULATE_AGE=$(( _CALCULATE_AGE - 1 )) ||
  [ $2 -gt $curmonth ] && _CALCULATE_AGE=$(( _CALCULATE_AGE -1 ))
}

## Function to check for valid Day
function _valid_day() {
  ## Check for valid year and compare with current date
  if [[ "$3" =~ ^*[!0-9]*$ ]] || [ "$3" -gt $( date +%Y ) ]
  then
    return 1

  elif [ "$3" -eq $( date +%Y ) ]
  then
    [ "$2" -gt $( date +%m ) ] && return 1 ||
    [ "$2" -eq $( date +%m ) ] && [ "$1" -gt $( date +%d ) ] && return 1
  fi

  ## Check for valid day and month
  [ $1 -gt 0 ] && [ $2 -le 12 ] &&
  if [[ "$2" =~ ^0?2$ ]]
  then
    [ "$1" -lt 29 ] && return 0 || return 1

  elif [[ "$2" =~ ^0?[4,6,9]|11$ ]]
  then
    [ "$1" -le 30 ] && return 0 || return 1

  elif [[ "$2" =~ ^0?[1,3,5,7,8]|10|12$ ]]
  then
    [ "$1" -le 31 ] && return 0 || return 1
  fi || return 1
}

## MAIN FUNCTION

for i in {1..2}
do
  printf "Enter name person number %i: " "$i"
  read name[i]
  printf "Enter his/her birthday    : "
  read day[i] month[i] year[i]

  _valid_day ${day[i]} ${month[i]} ${year[i]} &&
  _calculate_age ${day[i]} ${month[i]} ${year[i]} &&
  result[i]=$_CALCULATE_AGE && continue ||
  printf "Input Error, try again!\n" >&2 && exit 1
done

## Check who is older and print
if [ ${result[1]} -gt ${result[2]} ]
then
  printf "%s is older and his/her age is: %d\n" "${name[1]}" "${result[1]}"
  exit 0
elif [ ${result[1]} -lt ${result[2]} ]
then
  printf "%s is older and his/her age is: %d\n" "${name[2]}" "${result[2]}"
  exit 0
else
  printf "%s and %s is at the same age and their age is %d\n" "${name[1]}" "${name[2]}" "${result[1]}"
fi
